[versions]
jib = "3.5.1"
aws-lambda-java-core = "1.4.0"
aws-lambda-java-events = "3.16.1"
aws-lambda-java-runtimeinterfaceclient = "2.8.7"

[libraries]
aws-lambda-java-core = { module = "com.amazonaws:aws-lambda-java-core", version.ref = "aws-lambda-java-core" }
aws-lambda-java-events = { module = "com.amazonaws:aws-lambda-java-events", version.ref = "aws-lambda-java-events" }
aws-lambda-java-runtimeinterfaceclient = { module = "com.amazonaws:aws-lambda-java-runtime-interface-client", version.ref = "aws-lambda-java-runtimeinterfaceclient" }

[plugins]
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
